name = "Psychrometrics"
uuid = "89d1cb86-bf84-46ce-bdfb-ab7f830013b1"
authors = ["Alexandre Umpierre (aumpierre@gmail.com)"]
version = "0.1.2-alpha"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
