name = "Psychrometrics"
uuid = "21f87c03-21d6-4055-8023-3c3cf69bf667"
authors = ["Alexandre Umpierre (aumpierre@gmail.com)"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
