name = "Psychrometrics"
uuid = "341d3460-0126-454d-8dee-7369ac570df5"
authors = ["Alexandre Umpierre (aumpierre@gmail.com)"]
version = "0.1.1-alpha"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
